---
Name: userformsconditionalrecipient
After:
  - 'userforms/*'
---
UserDefinedForm:
  extensions:
    - ConditionalRecipientUserDefinedFormExtension
UserDefinedForm_EmailRecipient:
  extensions:
    - ConditionalRecipientUserDefinedFormRecipientExtension